name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'invest.gs'
      - 'appsscript.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install clasp
        run: npm install -g @google/clasp
      
      - name: Configure clasp credentials
        run: |
          echo '${{ secrets.CLASP_CREDENTIALS }}' > ~/.clasprc.json
          echo '${{ secrets.CLASP_CONFIG }}' > .clasp.json
          chmod 600 ~/.clasprc.json
          chmod 600 .clasp.json
      
      - name: Verify credentials setup
        run: |
          echo "Checking if credential files exist..."
          ls -la ~/.clasprc.json || echo "~/.clasprc.json not found"
          ls -la .clasp.json || echo ".clasp.json not found"
          echo "Checking file sizes..."
          wc -c ~/.clasprc.json .clasp.json
          echo "Testing clasp status..."
          clasp status || echo "clasp status failed"
      
      - name: Deploy to Google Apps Script
        run: clasp push
      
      - name: Deployment complete
        run: |
          echo "Deployment successful!"
          echo "View your script at: https://script.google.com"
