name: Deploy to Google Apps Script

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'invest.gs'
      - 'appsscript.json'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install clasp
        run: npm install -g @google/clasp
      
      - name: Configure clasp credentials
        run: |
          echo "$CLASP_CREDENTIALS" > ~/.clasprc.json
          echo "$CLASP_CONFIG" > .clasp.json
        env:
          CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
          CLASP_CONFIG: ${{ secrets.CLASP_CONFIG }}
      
      - name: Deploy to Google Apps Script
        run: clasp push
      
      - name: Deployment complete
        run: |
          echo "Deployment successful!"
          echo "View your script at: https://script.google.com"
